//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.08 at 12:47:21 PM EET 
//


package com.playtech.wallet.domain.messages;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.playtech.wallet.domain.messages package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _WalletChangeMessage_QNAME = new QName("", "walletChangeMessage");
    private final static QName _Player_QNAME = new QName("", "player");
    private final static QName _WalletChangeResult_QNAME = new QName("", "walletChangeResult");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.playtech.wallet.domain.messages
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link WalletChangeMessage }
     *
     */
    public WalletChangeMessage createWalletChangeMessage() {
        return new WalletChangeMessage();
    }

    /**
     * Create an instance of {@link WalletChangeResult }
     *
     */
    public WalletChangeResult createWalletChangeResult() {
        return new WalletChangeResult();
    }

    /**
     * Create an instance of {@link PlayerMessage }
     *
     */
    public PlayerMessage createPlayerMessage() {
        return new PlayerMessage();
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link WalletChangeMessage }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "walletChangeMessage")
    public JAXBElement<WalletChangeMessage> createWalletChangeMessage(WalletChangeMessage value) {
        return new JAXBElement<WalletChangeMessage>(_WalletChangeMessage_QNAME, WalletChangeMessage.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link PlayerMessage }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "player")
    public JAXBElement<PlayerMessage> createPlayer(PlayerMessage value) {
        return new JAXBElement<PlayerMessage>(_Player_QNAME, PlayerMessage.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link WalletChangeResult }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "walletChangeResult")
    public JAXBElement<WalletChangeResult> createWalletChangeResult(WalletChangeResult value) {
        return new JAXBElement<WalletChangeResult>(_WalletChangeResult_QNAME, WalletChangeResult.class, null, value);
    }

}
