//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.08 at 12:47:21 PM EET 
//


package com.playtech.wallet.domain.messages;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for walletChangeResultStatus.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="walletChangeResultStatus">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="OK"/>
 *     &lt;enumeration value="NO_SUCH_PLAYER"/>
 *     &lt;enumeration value="PLAYER_BALANCE_LESS_THAN_ZERO"/>
 *     &lt;enumeration value="REPEATING_TRANSACTION"/>
 *     &lt;enumeration value="OPTIMISTIC_LOCKING_EXCEPTION"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "walletChangeResultStatus")
@XmlEnum
public enum WalletChangeResultStatus {

    OK,
    NO_SUCH_PLAYER,
    PLAYER_BALANCE_LESS_THAN_ZERO,
    REPEATING_TRANSACTION,
    OPTIMISTIC_LOCKING_EXCEPTION;

    public String value() {
        return name();
    }

    public static WalletChangeResultStatus fromValue(String v) {
        return valueOf(v);
    }

}
