//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.08 at 12:47:21 PM EET 
//


package com.playtech.wallet.domain.messages;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import java.math.BigDecimal;


/**
 * <p>Java class for walletChangeResult complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="walletChangeResult">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="balanceChange" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="balanceVersion" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="errorCode" type="{}walletChangeResultStatus" minOccurs="0"/>
 *         &lt;element name="totalBalance" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="transactionId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "walletChangeResult", propOrder = {
    "balanceChange",
    "balanceVersion",
    "errorCode",
    "totalBalance",
    "transactionId"
})
public class WalletChangeResult {

    protected BigDecimal balanceChange;
    protected Long balanceVersion;
    protected WalletChangeResultStatus errorCode;
    protected BigDecimal totalBalance;
    protected String transactionId;

    /**
     * Gets the value of the balanceChange property.
     * 
     * @return
     *     possible object is
     *     {@link java.math.BigDecimal }
     *
     */
    public BigDecimal getBalanceChange() {
        return balanceChange;
    }

    /**
     * Sets the value of the balanceChange property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigDecimal }
     *
     */
    public void setBalanceChange(BigDecimal value) {
        this.balanceChange = value;
    }

    /**
     * Gets the value of the balanceVersion property.
     *
     * @return
     *     possible object is
     *     {@link Long }
     *
     */
    public Long getBalanceVersion() {
        return balanceVersion;
    }

    /**
     * Sets the value of the balanceVersion property.
     *
     * @param value
     *     allowed object is
     *     {@link Long }
     *
     */
    public void setBalanceVersion(Long value) {
        this.balanceVersion = value;
    }

    /**
     * Gets the value of the errorCode property.
     *
     * @return
     *     possible object is
     *     {@link WalletChangeResultStatus }
     *
     */
    public WalletChangeResultStatus getErrorCode() {
        return errorCode;
    }

    /**
     * Sets the value of the errorCode property.
     *
     * @param value
     *     allowed object is
     *     {@link WalletChangeResultStatus }
     *
     */
    public void setErrorCode(WalletChangeResultStatus value) {
        this.errorCode = value;
    }

    /**
     * Gets the value of the totalBalance property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigDecimal }
     *
     */
    public BigDecimal getTotalBalance() {
        return totalBalance;
    }

    /**
     * Sets the value of the totalBalance property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigDecimal }
     *     
     */
    public void setTotalBalance(BigDecimal value) {
        this.totalBalance = value;
    }

    /**
     * Gets the value of the transactionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * Sets the value of the transactionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionId(String value) {
        this.transactionId = value;
    }

}
